#!/bin/sh
set -eu

cd /var/www/html

mkdir -p \
    storage/app/private \
    storage/app/public \
    storage/framework/cache/data \
    storage/framework/sessions \
    storage/framework/testing \
    storage/framework/views \
    storage/logs \
    bootstrap/cache

if [ ! -f vendor/autoload.php ]; then
    echo "Installing PHP dependencies..."
    composer install --no-interaction --prefer-dist
fi

if [ ! -f .env ] && [ "${APP_ENV:-local}" != "production" ]; then
    cp .env.example .env
fi

file_has_app_key=false
if [ -f .env ] && grep -Eq '^APP_KEY=.+$' .env; then
    file_has_app_key=true
fi

if [ -z "${APP_KEY:-}" ] && [ "$file_has_app_key" = "false" ]; then
    if [ "${APP_ENV:-local}" = "production" ]; then
        echo "APP_KEY must be provided when running the production image." >&2
        exit 1
    fi

    php artisan key:generate --force
fi

# A bind-mounted cache generated by host PHP can freeze host database values
# into the long-running development server. Production caches are managed by
# the production image/deployment and are intentionally left untouched.
if [ "${APP_ENV:-local}" != "production" ]; then
    php artisan config:clear --no-ansi
fi

chown -R www-data:www-data storage bootstrap/cache 2>/dev/null || true
chmod -R ug+rwX storage bootstrap/cache 2>/dev/null || true

if [ "${WAIT_FOR_DB:-true}" = "true" ] && [ "${DB_CONNECTION:-}" = "mysql" ]; then
    echo "Waiting for MySQL..."
    attempt=0

    until php -r '
        $host = getenv("DB_HOST") ?: "db";
        $port = getenv("DB_PORT") ?: "3306";
        $database = getenv("DB_DATABASE") ?: "carelink_tb";
        $username = getenv("DB_USERNAME") ?: "carelink";
        $password = getenv("DB_PASSWORD") ?: "carelink";

        try {
            $pdo = new PDO("mysql:host={$host};port={$port};dbname={$database}", $username, $password);
            $pdo->query("SELECT 1");
        } catch (Throwable $exception) {
            exit(1);
        }
    '; do
        attempt=$((attempt + 1))

        if [ "$attempt" -ge 60 ]; then
            echo "MySQL did not become ready within 120 seconds." >&2
            exit 1
        fi

        sleep 2
    done
fi

if [ "${AUTO_MIGRATE:-false}" = "true" ]; then
    php artisan migrate --force
fi

exec "$@"
